WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e8f12a7f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/945995b46aecae8f6c0a9603721e7e60/cookie
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e8ecb33a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/945995b46aecae8f6c0a9603721e7e60/cookie
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e8ecb3520>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/945995b46aecae8f6c0a9603721e7e60/cookie